### PR TITLE
fixes #8 and add special sea ice dataset to MOSAIC catalog

### LINKED ISSUE #8: Add FESOM2 data
First example dataset is here: https://zenodo.org/record/3819896

From the [the pyfesom2 docs](https://pyfesom2.readthedocs.io/), I gather that the mesh will be loaded from a Path. So we could use a Zip file and open it via [`zipfile`](https://docs.python.org/3/library/zipfile.html#module-zipfile). Not sure this is possible with tar archives as well?

### PR DESCRIPTION
**Pull request by suvarchal**
- add 2 FESOM2 catalogs based on zenodo 
- add simple example using the catalogs
- add special sea ice dataset to MOSAIC catalog

### CODE REVIEW

**Comment by willirath** [comment]
I'll have a look on Monday. Thanks for working on this!

**Comment by willirath** [comment]
I've played with the builtin caching of Intake in an earlier version of the NEMO catalogs and found it insufficient for our purpose for two reasons:

- Downloading the original data was unstable. As you said, resuming failed downloads is not supported. And for large files, downloads often seem to stall.

- It's difficult to share a cache with others on the same machine.

Hence, I went for splitting the logic into a home-rolled part that downloads from Zenodo and Intake for handling data after downloading.

See #9 for a solution that, given a DOI, fetches all data from Zenodo.

**Comment by suvarchal** [comment]
thanks for tthe feedback, 
 
> - Downloading the original data was unstable. As you said, resuming failed downloads is not supported. And for large files, downloads often seem to stall.

last week, while playing with it i realized download urls like https://zenodo.org/record/3819896/files/a_ice.fesom.1948.nc?download=1 (gzipped) or without urlparameter download=1 (raw) both were reporting wrong Content-Length in the response, among other issues this can cause depending on download client, it rendered progress/staus of downloads of any client useless, and it seemed a bit unstable too. But then there is download url  from api like: https://zenodo.org/api/files/718572ad-74ff-44ea-8d73-d385e74fc06b/temp.fesom.1948.nc was more stable, right content-length, moreover all the api links of a dataset can be requested in json like:https://zenodo.org/record/3819896/export/json, that can make it easy to build catalogs programmatically.   Since Thursday after a few hours of unstable zenodo server(s) and then content-length was fixed, now for smaller fesom2 files i don't see any difference between non api download and api download. I wonder what would it be now to use use it on larger NEMO datasets, i will try that out. 

> - It's difficult to share a cache with others on the same machine.

using ( not well documented ) regex parameter on cache that seems possible? i guess should prepare a better example.
 

in anycase, downloading larger datasets and without partial downloads, zenodo doesn't seem to be friendly option for larger datasets, i will share the opendap server ( could be zarr later), so that test datasets could lie there too, and wouldn't need to be downloaded.

**Comment by willirath** [comment]
See <https://nbviewer.jupyter.org/github/ESM-VFC/esm-vfc-catalogs/blob/4e40a277ae9568167593ffa737209ebe81c81097/examples/fetch_based_on_zenodo_doi.ipynb> from #9 for a simplified examples that avoids Intake caching entirely.

**Comment by willirath** [comment]
This is mostly superceded by #9.

**Comment by willirath** [comment]
I've cherry-picked the MOSAIC catalog entry already and also adapted the FESOM2 entry in #9. So I'll close here.

**Pull request closed without merging**
